### ISSUE TITLE
not clear how to access buckets

### ISSUE THREAD

**Issue by pieper** [ImagingDataCommons/IDC-Docs#3]
Need to add sample url and example command line to give people the idea how to use the data.

https://learn.canceridc.dev/data/organization-of-data#storage-buckets

**Comment by fedorov** [comment]
@pieper I made some edits to clarify on that page. There is already an example command showing how to get the data. Can you take a look and let me know if you have specific suggestions for improvement?

**Comment by pieper** [comment]
@fedorov thanks for working on this.  I like that there is a `gsutil` command line example and links to the notebook explaining how to get data.

In terms of specific suggestions, we tell people to use BQ and not manifest files but we only give them the simple example of the file list.  Could we make an example that lays out the following steps: (1) make a manifest in BQ using the web app, (2) using the `bq` command to see the list of studies in your cohort, (3) piping the file list for a selected study into a `gsutil` to download.

I think this would be helpful for people wanting to iterate through studies or download different studies to different VMs for parallel processing.  I haven't tried using `bq` in this way but it should be possible.

Also I noticed that this link is dead:

![image](https://user-images.githubusercontent.com/126077/130150084-15c7182c-be22-4694-a6ef-bf5c83d3c902.png)

**Comment by fedorov** [comment]
We revisited download instructions to hopefully make this more clear - please reopen if this is not the case.

https://learn.canceridc.dev/data/downloading-data
